
spring.neo4j:
  uri: neo4j://localhost:7687
  authentication:
    username: neo4j
    password: asdqwe123
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging.level.org.neo4j.ogm.drivers.bolt.request.BoltRequest: DEBUG